module.exports = {
  locales: {
    "/": {
      lang: "English",
      title: "NuShell",
      description: "A new type of shell.",
    },
    "/es/": {
      lang: "Español",
      title: "NuShell",
      description: "A new type of shell.",
    },
    "/ja/": {
      lang: "日本語",
      title: "NuShell",
      description: "A new type of shell.",
    },
    "/pt-BR/": {
      lang: "Português do Brasil",
      title: "NuShell",
      description: "A new type of shell.",
    },
    "/zh-cn/": {
      lang: "官话",
      title: "NuShell",
      description: "A new type of shell.",
    },
  },
  head: [
    ["meta", { name: "theme-color", content: "#3eaf7c" }],
    ["meta", { name: "apple-mobile-web-app-capable", content: "yes" }],
    [
      "meta",
      { name: "apple-mobile-web-app-status-bar-style", content: "black" },
    ],
  ],
  themeConfig: {
    repo: "",
    editLinks: false,
    docsDir: "",
    editLinkText: "",
    lastUpdated: false,
    nav: [
      {
        text: "Book",
        link: "/book/",
      },
      {
        text: "Github",
        link: "https://github.com/nushell/nushell",
      },
    ],
    sidebar: {
      "/book/": [
        {
          title: "Nu Book",
          collapsable: false,
          children: [
            "installation",
            "introduction",
            "moving_around",
            "types_of_data",
            "loading_data",
            "working_with_tables",
            "pipeline",
            "configuration",
            "aliases",
            "math",
            "environment",
            "metadata",
            "shells_in_shells",
            "escaping",
            "plugins",
            "coming_from_bash",
            "nushell_map",
            "nushell_map_imperative",
            "nushell_map_functional",
            "nushell_operator_map",
          ],
        },
      ],
      "/es/book/": [
        {
          title: "Nu Book",
          collapsable: false,
          children: [
            "instalacion",
            "introduccion",
            "explorando",
            "tipos_de_datos",
            "cargando_datos",
            "trabajando_con_tablas",
            "pipeline",
            "configuracion",
            "aliases",
            "matematicas",
            "entorno",
            "metadatos",
            "shells_en_shells",
            "escapando",
            "plugins",
            "llegando_de_bash",
            "mapa_nushell",
            "mapa_imperativo_nushell",
            "mapa_funcional_nushell",
            "mapa_operador_nushell",
          ],
        },
      ],
      "/ja/book/": [
        {
          title: "Nu Book",
          collapsable: false,
          children: [
            "installation",
            "introduction",
            "moving_around",
            "types_of_data",
            "loading_data",
            "working_with_tables",
            "pipeline",
            "configuration",
            "metadata",
            "shells_in_shells",
            "escaping",
            "plugins",
          ],
        },
      ],
      "/pt-BR/book/": [
        {
          title: "Nu Book",
          collapsable: false,
          children: [
            "instalacao",
            "introducao",
            "explorando",
            "tipos_de_dados",
            "carregando_dados",
            "trabalhando_com_tabelas",
            "pipeline",
            "metadados",
            "shells_em_shells",
            "escapando",
            "plugins",
          ],
        },
      ],
      "/zh-cn/book/": [
        {
          title: "Nu Book",
          collapsable: false,
          children: [
            "installation",
            "introduction",
            "moving_around",
            "types_of_data",
            "loading_data",
            "working_with_tables",
            "pipeline",
            "configuration",
            "aliases",
            "math",
            "environment",
            "metadata",
          ],
        },
      ],
    },
  },
  plugins: ["@vuepress/plugin-back-to-top", "@vuepress/plugin-medium-zoom"],
};
